name: gymtesis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.1
  date_picker_timeline: ^1.2.3
  fl_chart: 0.61.0
  provider: ^6.0.5
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  firebase_auth: ^4.1.3
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.17
  # intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  visibility_detector: ^0.4.0+2
  flick_video_player: ^0.5.0
  
  dots_indicator: ^2.1.0
  # youtube_player_iframe: ^4.0.4
  # cached_network_image: ^3.2.3
  # appinio_video_player: ^1.2.0
  # youtube_player_flutter: ^8.1.2
  # fullscreen: ^1.0.3
  percent_indicator: ^4.2.3
  chewie: ^1.3.6
  video_player: ^2.6.1
  audioplayers: ^4.1.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0
  # device_preview: ^1.1.0
  dio: 4.0.0
  path_provider: ^2.0.12
  open_file: 3.2.1
  file_picker: 4.1.3
  flutter_localization: ^0.1.12
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
flutter_icons: 
  android: true
  ios: true
  image_path: "assets/img/logo2.png"
  web:
    generate: true
    image_path: "assets/img/logo2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/logo2.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/logo2.png"


  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#FFFFFF"
  image: assets/img/logoF.jpg

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/box.png
    - assets/img/5beiKJ01 (1).svg
    - assets/img/success-svgrepo-com.svg
    - assets/img/23376f99-9fd2-40a6-92ef-810ceffa99c9.jpg
    - assets/img/256913e7-dc60-41f1-8b07-cd4057cb8b44-removebg-preview.png
    - assets/img/flexifi.png
    - assets/img/no-profile-photo.jpg
    - assets/img/playa.jpg
    - assets/img/logoF.jpg
    - assets/img/R (5).jpg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
